### ISSUE TITLE
BigQuery write error invalid partition decorator `$YYYYMDD` instead of `$YYYYMMDD`

### ISSUE THREAD

**Issue by charlesverdad** [wepay/kafka-connect-bigquery#104]
I've been having this problem with my connector:

```
[2018-02-26 11:34:16,607] INFO Decreased batch size to 1 for {datasetId=myproj_staging, tableId=dbz_myproj_mycompany_public_skills$2018226} (com.wepay.kafka.connect.bigquery.write.batch.DynamicBatchWriter:277)
[2018-02-26 11:34:16,791] ERROR WorkerSinkTask{id=kcbq-myproj-mycompany-0} Offset commit failed, rewinding to last committed offsets (org.apache.kafka.connect.runtime.WorkerSinkTask:351)
com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException: Exception occurred while executing write threads
	at com.wepay.kafka.connect.bigquery.BigQuerySinkTask.flush(BigQuerySinkTask.java:238)
	at org.apache.kafka.connect.sink.SinkTask.preCommit(SinkTask.java:117)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:345)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:182)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException: Attempted to decrease batchSize below 1
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.wepay.kafka.connect.bigquery.BigQuerySinkTask.flush(BigQuerySinkTask.java:233)
	... 11 more
Caused by: com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException: Attempted to decrease batchSize below 1
	at com.wepay.kafka.connect.bigquery.write.batch.DynamicBatchWriter.decreaseBatchSize(DynamicBatchWriter.java:274)
	at com.wepay.kafka.connect.bigquery.write.batch.DynamicBatchWriter.seekingWriteAll(DynamicBatchWriter.java:152)
	at com.wepay.kafka.connect.bigquery.write.batch.DynamicBatchWriter.writeAll(DynamicBatchWriter.java:101)
	at com.wepay.kafka.connect.bigquery.BigQuerySinkTask$TableWriter.call(BigQuerySinkTask.java:154)
	at com.wepay.kafka.connect.bigquery.BigQuerySinkTask$TableWriter.call(BigQuerySinkTask.java:131)
	... 4 more

```
My configuration is

```
    {
      "name": "kcbq-myproj-mycompany",
      "config": {
        "connector.class": "com.wepay.kafka.connect.bigquery.BigQuerySinkConnector",
        "tasks.max": "1",
        "topics": "dbz_myproj_mycompany.public.skills",
        "autoCreateTables": "true",
        "autoUpdateSchemas": "true",
        "sanitizeTopics": "true",
        "schemaRetriever": "com.wepay.kafka.connect.bigquery.schemaregistry.schemaretriever.SchemaRegistrySchemaRetriever",
        "schemaRegistryLocation": "http://mc-schema-registry:80",
        "bufferSize": "100000",
        "maxWriteSize": "10000",
        "tableWriteWait": "1000",
        "project": "mycompany-platform",
        "datasets": ".*=myproj_staging",
        "keyfile": "/etc/gcloud/creds/mc_kafka.json"
      }
    }
```

I think it has something to do with the tableId it's trying to write to `tableId=dbz_myproj_mycompany_public_skills$2018226`. The partition decorator looks like it's missing a zero (I think it should be `20180226` instead of `2018226`.)

**Comment by charlesverdad** [comment]
Update:

I switched to the `SingleBatchWriter` and was able to get a more detailed Exception. It seems the tableId really is the problem:

```

Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "The destination table's partition dbz_abelian_kalibrr_public_skills$2018226 is outside the allowed bounds. You can only stream to partitions within 0 days in the past and 0 days in the future relative to the current date.",
    "reason" : "invalid"
  } ],
  "message" : "The destination table's partition dbz_abelian_kalibrr_public_skills$2018226 is outside the allowed bounds. You can only stream to partitions within 0 days in the past and 0 days in the future relative to the current date.",
  "status" : "INVALID_ARGUMENT"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at com.google.cloud.bigquery.spi.DefaultBigQueryRpc.insertAll(DefaultBigQueryRpc.java:283)
	... 10 more

```

**Comment by criccomini** [comment]
@mtagle This looks like it might be a bug in how we handle table partitions?

**Comment by criccomini** [comment]
@charlesverdad What version are you running? This was a known issue that we fixed on master, I believe.

**Comment by mtagle** [comment]
as far as I can tell, this should have been fixed with https://github.com/wepay/kafka-connect-bigquery/issues/104

**Comment by criccomini** [comment]
I closed this issue as fixed. @charlesverdad let us know if it's still occurring on master.

As far as the batch writing goes, the default batch writer tries to be smart. We have to write a batch of messages to BigQuery, but we don't know exactly how many we can write before BigQuery rejects it due to the payload being too big. To get around this, we write, and if we get an exception, we assume it's a batch-too-large exception, cut the batch size in half, and retry. If there's a non-recoverable exception, we eventually get to a batch size of 1, and we can't send 0 messages, so it fails at this point. This is what you were seeing.

**Comment by charlesverdad** [comment]
Ah okay. Thanks!
 I was using the tagged 1.0.0 release. I just noticed how old that was.
