### ISSUE TITLE
./connector.sh giving a NoSuchMethodError

### ISSUE THREAD

**Issue by fahimsakri** [wepay/kafka-connect-bigquery#105]
On Running `./connector.sh` command get this error. 

```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;
        at org.reflections.Reflections.expandSuperTypes(Reflections.java:380)
        at org.reflections.Reflections.<init>(Reflections.java:126)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanPluginPath(DelegatingClassLoader.java:258)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanUrlsAndAddPlugins(DelegatingClassLoader.java:201)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.initLoaders(DelegatingClassLoader.java:162)
        at org.apache.kafka.connect.runtime.isolation.Plugins.<init>(Plugins.java:47)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:75)
```

**Comment by criccomini** [comment]
This looks like a version conflict issue. We probably need to fix something to make versions match.

**Comment by whynick1** [comment]
@fahimsakri cc @criccomini 
We had the same issue before, and it turned out that dependency versions are outdated. We have updated build.gradle to solve this problem (check this commit: https://github.com/wepay/kafka-connect-bigquery/commit/6458236558c2314eced9e03a6f1f2bfb602a5cdd). It should work fine after you pull from the latest repository. Please let me know if you have any other issue.
