### ISSUE TITLE
Connector fails to start due to CLASSPATH issues on current master [MACOS]

### ISSUE THREAD

**Issue by pplaatje** [wepay/kafka-connect-bigquery#141]
Hi,

When using the current master with the instructions from the readme, the connector does not start on MacOs. It seems to be specifically due to the way that

`mkdir bin/jar/ && tar -C bin/jar/ -xf kcbq-confluent/build/distributions/kcbq-confluent-*.tar`

extracts the content into bin/jar/kcbq-confluent-1.1.0-SNAPSHOT/ instead of bin/jar directly? The exception thrown is:
```
[2018-09-28 12:21:32,123] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:100)
java.util.concurrent.ExecutionException: org.apache.kafka.connect.errors.ConnectException: Failed to find any class that implements Connector and which name matches com.wepay.kafka.connect.bigquery.BigQuerySinkConnector available connectors are: io.confluent.connect.hdfs.HdfsSinkConnector, org.apache.kafka.connect.source.SourceConnector, org.apache.kafka.connect.tools.VerifiableSourceConnector, org.apache.kafka.connect.file.FileStreamSinkConnector, org.apache.kafka.connect.file.FileStreamSourceConnector, org.apache.kafka.connect.tools.VerifiableSinkConnector, io.confluent.connect.hdfs.tools.SchemaSourceConnector, org.apache.kafka.connect.sink.SinkConnector, io.confluent.connect.jdbc.JdbcSourceConnector
	at org.apache.kafka.connect.util.ConvertingFutureCallback.result(ConvertingFutureCallback.java:80)
	at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:67)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:97)
Caused by: org.apache.kafka.connect.errors.ConnectException: Failed to find any class that implements Connector and which name matches com.wepay.kafka.connect.bigquery.BigQuerySinkConnector available connectors are: io.confluent.connect.hdfs.HdfsSinkConnector, org.apache.kafka.connect.source.SourceConnector, org.apache.kafka.connect.tools.VerifiableSourceConnector, org.apache.kafka.connect.file.FileStreamSinkConnector, org.apache.kafka.connect.file.FileStreamSourceConnector, org.apache.kafka.connect.tools.VerifiableSinkConnector, io.confluent.connect.hdfs.tools.SchemaSourceConnector, org.apache.kafka.connect.sink.SinkConnector, io.confluent.connect.jdbc.JdbcSourceConnector
	at org.apache.kafka.connect.runtime.Worker.getConnectorClass(Worker.java:226)
	at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:166)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.startConnector(StandaloneHerder.java:250)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:164)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:94)
```

When I add that specific directory to my classpath manually (export CLASSPATH="$CLASSPATH:$BASE_DIR/../../bin/jar/kcbq-confluent-1.1.0-SNAPSHOT/*") , the connector comntinues, but fails with a different error:

`Caused by: org.apache.kafka.common.config.ConfigException: Invalid value com.wepay.kafka.connect.bigquery.schemaregistry.schemaretriever.SchemaRegistrySchemaRetriever for configuration schemaRetriever: Class com.wepay.kafka.connect.bigquery.schemaregistry.schemaretriever.SchemaRegistrySchemaRetriever could not be found.`

Is the above a known issue, or am I doing something wrong? Thanks in advance!

**Comment by pplaatje** [comment]
Hi,

No I've just took the Confluent distribution locally on my mac and ran it from there. Version 1.1.0 seems to work however, not sure why though.

Cheers,
Patrick

**Comment by geopamplona** [comment]
how resolve this?
i have same issue
