### ISSUE TITLE
Class com.wepay.kafka.connect.bigquery.schemaregistry.schemaretriever.SchemaRegistrySchemaRetriever could not be found.

### ISSUE THREAD

**Issue by pplaatje** [wepay/kafka-connect-bigquery#146]
Hi there,

We're experiencing an issue with the distTar gradle command. It seems that running the `./gradlew clean distTar` does create the tar with all required jars, but is missing the kcbq-confluent jar (which should include the SchemaRegistrySchemaRetriever? When I run the connector the following exception is thrown:
```

ERROR Error while starting connector bigquery-connector (org.apache.kafka.connect.runtime.WorkerConnector:109)
com.wepay.kafka.connect.bigquery.exception.SinkConfigConnectException: Couldn't start BigQuerySinkConnector due to configuration error
	at com.wepay.kafka.connect.bigquery.BigQuerySinkConnector.start(BigQuerySinkConnector.java:152)
	at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:101)
	at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:126)
	at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:183)
	at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:178)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.startConnector(StandaloneHerder.java:250)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:164)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:94)
Caused by: org.apache.kafka.common.config.ConfigException: Invalid value com.wepay.kafka.connect.bigquery.schemaregistry.schemaretriever.SchemaRegistrySchemaRetriever for configuration schemaRetriever: Class com.wepay.kafka.connect.bigquery.schemaregistry.schemaretriever.SchemaRegistrySchemaRetriever could not be found.
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:724)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:469)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:462)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:62)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:75)
	at com.wepay.kafka.connect.bigquery.config.BigQuerySinkConfig.<init>(BigQuerySinkConfig.java:517)
	at com.wepay.kafka.connect.bigquery.config.BigQuerySinkConnectorConfig.<init>(BigQuerySinkConnectorConfig.java:79)
	at com.wepay.kafka.connect.bigquery.BigQuerySinkConnector.start(BigQuerySinkConnector.java:150)
	... 7 more

```

Any ideas?

Thanks!
-patrick

**Comment by Riduidel** [comment]
Hey, can you explain how you had the connector working ? I'm having exactly the same issue ... and i hope your solution can help me.
