### ISSUE TITLE
IllegalArgumentException causing offset commit failure & streaming of many duplicates

### ISSUE THREAD

**Issue by SwamWithTurtles** [wepay/kafka-connect-bigquery#151]
Hey!

We're using this connector to try and stream a dataset of around 3.2m rows to BigQuery (at around 6.5k messages/second). It works great at first but at some point in the dataset we're seeing it fail - when it does so, it just continues to arbitrarily stream data (looks like offsets are not commited but connector is not paused so it just continues to stream the same data?)

We see both these error messages in the log:

> [2019-02-14 07:48:38,140] ERROR WorkerSinkTask{id=connector-name-0} Offset commit failed, rewinding to last committed offsets (org.apache.kafka.connect.runtime.WorkerSinkTask:386)
> com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException: Some write threads encountered unrecoverable errors: java.lang.IllegalArgumentException; See logs for more detail
>         at com.wepay.kafka.connect.bigquery.write.batch.KCBQThreadPoolExecutor.awaitCurrentTasks(KCBQThreadPoolExecutor.java:95)
>         at com.wepay.kafka.connect.bigquery.BigQuerySinkTask.flush(BigQuerySinkTask.java:97)
>         at org.apache.kafka.connect.sink.SinkTask.preCommit(SinkTask.java:125)
>         at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:380)
>         at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:210)
>         at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:194)
>         at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
>         at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)
> [2019-02-14 07:48:38,140] ERROR WorkerSinkTask{id=connector-name-0} Commit of offsets threw an unexpected exception for sequence number 3: null (org.apache.kafka.connect.runtime.WorkerSinkTask:261)
> com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException: Some write threads encountered unrecoverable errors: java.lang.IllegalArgumentException; See logs for more detail
>         at com.wepay.kafka.connect.bigquery.write.batch.KCBQThreadPoolExecutor.awaitCurrentTasks(KCBQThreadPoolExecutor.java:95)
>         at com.wepay.kafka.connect.bigquery.BigQuerySinkTask.flush(BigQuerySinkTask.java:97)
>         at org.apache.kafka.connect.sink.SinkTask.preCommit(SinkTask.java:125)
>         at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:380)
>         at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:210)
>         at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:194)
>         at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
>         at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)

and:

> [2019-02-14 07:36:14,504] ERROR Task failed with java.lang.IllegalArgumentException error: null (com.wepay.kafka.connect.bigquery.write.batch.KCBQThreadPoolExecutor:66)
> Exception in thread "pool-32-thread-4" java.lang.IllegalArgumentException
>         at com.google.api.client.repackaged.com.google.common.base.Preconditions.checkArgument(Preconditions.java:111)
>         at com.google.api.client.util.Preconditions.checkArgument(Preconditions.java:37)
>         at com.google.api.client.json.JsonGenerator.serialize(JsonGenerator.java:135)
>         at com.google.api.client.json.JsonGenerator.serialize(JsonGenerator.java:172)
>         at com.google.api.client.json.JsonGenerator.serialize(JsonGenerator.java:172)
>         at com.google.api.client.json.JsonGenerator.serialize(JsonGenerator.java:145)
>         at com.google.api.client.json.JsonGenerator.serialize(JsonGenerator.java:172)
>         at com.google.api.client.json.JsonGenerator.serialize(JsonGenerator.java:106)
>         at com.google.api.client.http.json.JsonHttpContent.writeTo(JsonHttpContent.java:78)
>         at com.google.api.client.http.GZipEncoding.encode(GZipEncoding.java:49)
>         at com.google.api.client.http.HttpEncodingStreamingContent.writeTo(HttpEncodingStreamingContent.java:51)
>         at com.google.api.client.util.IOUtils.computeLength(IOUtils.java:113)
>         at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:927)
>         at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
>         at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
>         at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
>         at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.insertAll(HttpBigQueryRpc.java:281)
>         at com.google.cloud.bigquery.BigQueryImpl.insertAll(BigQueryImpl.java:445)
>         at com.wepay.kafka.connect.bigquery.write.row.SimpleBigQueryWriter.performWriteRequest(SimpleBigQueryWriter.java:65)
>         at com.wepay.kafka.connect.bigquery.write.row.BigQueryWriter.writeRows(BigQueryWriter.java:117)
>         at com.wepay.kafka.connect.bigquery.write.batch.TableWriter.run(TableWriter.java:77)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)

Is this a known issue, or one that's easy to debug through a means I'm simply missing? 

There's a chance it may be a data set issue (though I'm less convinced on that because it's failing at different points on different runs), but even so, I'd expect the connector to robustly handle that. Any ideas?

**Comment by SwamWithTurtles** [comment]
Hi all,

Just an update here: we discovered the root cause which was trying to stream "Inf" into the table. This meets the IEEE spec for floats; but not the JSON spec so it's failing on Google's BigQuery API. I think it's reasonable that you fail here.

**However**, I do feel like there's still a weirdness here - the connector is not handling the error case correctly. It shouldn't start streaming duplicates, it should fail more catastrophically.

David

**Comment by jcondit** [comment]
The BQ API accepts the string "Infinity" in the JSON object for cases where you want to stream the float Infinity into a table, and the BQ Java client library looks like it will correctly pass this string through. However, the BQ Java client library won't do the conversion automatically, so the client code must substitute string "Infinity" for float Infinity as appropriate.

Ideally the Java client library would do this automatically, and we can consider it for a future version. At the very least, I agree it should fail more gracefully. :-)

**Comment by vdesabou** [comment]
In case anyone found this, this should be handled now by this configuration:

```
convertDoubleSpecialValues
Designates whether +Infinity is converted to Double.MAX_VALUE and whether -Infinity and NaN are converted to Double.MIN_VALUE to ensure successfull delivery to BigQuery.

Type: boolean
Default: false
Importance: low
```
