### ISSUE TITLE
NullPointerException on the Schema Type

### ISSUE THREAD

**Issue by J314Y** [wepay/kafka-connect-bigquery#152]
Hey, I'm trying out this bigquery connector but getting:
``` 
"trace": "org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
      		at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:586)
      		at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
      		at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
      		at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
      		at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
      		at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
      		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
      		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      		at java.lang.Thread.run(Thread.java:748)
      Caused by: java.lang.NullPointerException
      		at com.wepay.kafka.connect.bigquery.convert.BigQueryRecordConverter.convertRecord(BigQueryRecordConverter.java:69)
      		at com.wepay.kafka.connect.bigquery.convert.BigQueryRecordConverter.convertRecord(BigQueryRecordConverter.java:51)
      		at com.wepay.kafka.connect.bigquery.BigQuerySinkTask.getRecordRow(BigQuerySinkTask.java:143)
      		at com.wepay.kafka.connect.bigquery.BigQuerySinkTask.put(BigQuerySinkTask.java:165)
      		at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:564)
      		... 10 more
```
What I am doing differently is I only have a kafka connect, schema registry service and kafka topics up and running out of the confluent platform. This is on version 1.1.0 which is the latest stable. Any advice on how to troubleshoot this?
https://github.com/wepay/kafka-connect-bigquery/blob/1.1.0/kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/convert/BigQueryRecordConverter.java#L69

**Comment by C0urante** [comment]
@J314Y the connector requires messages that it handles to have schemas, and this NPE appears to be resulting from the connector reading a message that doesn't have one.

Can you provide the following?

- The worker configuration for Kafka Connect (e.g., `connect-distributed.properties` or `connect-standalone.properties`)
- The configuration for the connector itself
- A message from a topic the connector is consuming from, or, if that isn't possible, the process you used to write that data into Kafka initially

**Comment by J314Y** [comment]
Worker Configuration:
```kafka-connect.properties (distributed)

log4j.root.loglevel=DEBUG
plugin.path=/usr/share/java,/usr/share/confluent-hub-components
rest.advertised.host.name=10.51.103.10
rest.port=8083
group.id=kafka-connect-dev
bootstrap.servers=<redacted>
schema.registry.url=<redacted>

key.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
key.converter.schema.registry.url=<redacted>

value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false
value.converter.schema.registry.url=<redacted>

internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false

internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter.schemas.enable=false

config.storage.replication.factor=3
status.storage.replication.factor=3
offset.storage.replication.factor=3

config.storage.topic=kafka-connect-dev-cp-kafka-connect-config
status.storage.topic=kafka-connect-dev-cp-kafka-connect-status
offset.storage.topic=kafka-connect-dev-cp-kafka-connect-offset

sasl.mechanism=PLAIN
security.protocol=SASL_SSL
sasl.jaas.config=<redacted>

producer.sasl.mechanism=PLAIN
producer.security.protocol=SASL_SSL
producer.sasl.jaas.config=<redacted>

consumer.sasl.mechanism=PLAIN
consumer.security.protocol=SASL_SSL
consumer.sasl.jaas.config=<redacted>
```

Configuration for the connector:
```
{
  "name": "kafka-bigquery-test",
  "config": {
    "connector.class": "com.wepay.kafka.connect.bigquery.BigQuerySinkConnector",
    "tasks.max": "2",
    "topics": "bigquerysink",
    "project": "projectname",
    "datasets": ".*=datasetname",
    "keyfile": "/usr/share/application_credentials.json",
    "schemaRegistryLocation": "<redacted>",
    "schema.registry.url": "<redacted>",
    "autoCreateTables": true,
    "autoUpdateSchemas": true,
    "topicsToTables": "(.*)=$1",
    "schemaRetriever": "com.wepay.kafka.connect.bigquery.schemaregistry.schemaretriever.SchemaRegistrySchemaRetriever"
  }
}
```
The message is any json blob. I've been passing {"name": "Justin"}

**Comment by C0urante** [comment]
@J314Y the `value.converter` you're using for the connector is configured to not use schemas. You can try setting `value.converter.schemas.enable` to `true`, or, probably better, use the Confluent AvroConverter (which automatically includes schemas with messages) instead of the Kafka JsonConverter.

**Comment by J314Y** [comment]
ah yep i just tried this out and its working now

**Comment by Kukreti12** [comment]
It is working as expected by updating in worker configuration property
optional
`key.converter=org.apache.kafka.connect.storage.StringConverter`
`value.converter.schemas.enable=false`
Required
`value.converter=io.confluent.connect.avro.AvroConverter`
