### ISSUE TITLE
Using bigquery connector but am not finding the data in kafka load into BQ

### ISSUE THREAD

**Issue by J314Y** [wepay/kafka-connect-bigquery#153]
Hey for some reason my connector for BQ isn't throwing errors or populating the tables. I'm wondering if someone can help me troubleshoot or verify that the parameters for my BQ connector are right. Below is what happens when i do a details:

```
curl -s -H "Content-Type: application/json" -X GET  http://localhost:8083/connectors/kafka-bigquery-test | jq .

{
  "name": "kafka-bigquery-test",
  "config": {
    "connector.class": "com.wepay.kafka.connect.bigquery.BigQuerySinkConnector",
    "autoUpdateSchemas": "true",
    "autoCreateTables": "true",
    "tasks.max": "2",
    "topics": "bigquerysink",
    "schemaRegistryLocation": "<redacted>",
    "topicsToTables": "(.*)=$1",
    "project": "myproject-198519",
    "datasets": ".*=dataset_test",
    "schema.registry.url": "<redacted>",
    "keyfile": "<redacted>",
    "name": "kafka-bigquery-test",
    "schemaRetriever": "com.wepay.kafka.connect.bigquery.schemaregistry.schemaretriever.SchemaRegistrySchemaRetriever",
    "bufferSize": "10"
  },
  "tasks": [
    {
      "connector": "kafka-bigquery-test",
      "task": 0
    },
    {
      "connector": "kafka-bigquery-test",
      "task": 1
    }
  ],
  "type": "sink"
}
```

Under this structure I would expect my data to live in the table: `myproject-198519.dataset_test.bigquerysink` but nothing is populating. I can also provide the schema registry subjects. The way im sending data is using the python-avro-confluent module AvroProducer. I can also verify that data is being sent to the the Kafka topic by using the consumer or just cli. Any ideas?

**Comment by J314Y** [comment]
Looking at the logs of the server I actually found the following. Anyone have any idea what can cause a connect timeout?

```org.apache.kafka.connect.errors.ConnectException: Exception encountered while trying to fetch latest schema metadata from Schema Registry
	at com.wepay.kafka.connect.bigquery.schemaregistry.schemaretriever.SchemaRegistrySchemaRetriever.retrieveSchema(SchemaRegistrySchemaRetriever.java:67)
	at com.wepay.kafka.connect.bigquery.SchemaManager.createTable(SchemaManager.java:48)
	at com.wepay.kafka.connect.bigquery.BigQuerySinkConnector.ensureExistingTables(BigQuerySinkConnector.java:113)
	at com.wepay.kafka.connect.bigquery.BigQuerySinkConnector.ensureExistingTables(BigQuerySinkConnector.java:136)
	at com.wepay.kafka.connect.bigquery.BigQuerySinkConnector.start(BigQuerySinkConnector.java:155)
	at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:111)
	at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:136)
	at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:195)
	at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:241)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:916)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1300(DistributedHerder.java:111)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$15.call(DistributedHerder.java:932)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$15.call(DistributedHerder.java:928)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:153)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:188)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.getLatestVersion(RestService.java:359)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.getLatestVersion(RestService.java:351)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getLatestSchemaMetadata(CachedSchemaRegistryClient.java:136)
	at com.wepay.kafka.connect.bigquery.schemaregistry.schemaretriever.SchemaRegistrySchemaRetriever.retrieveSchema(SchemaRegistrySchemaRetriever.java:63)
	... 16 more```

**Comment by J314Y** [comment]
this was due to incorrect settings for the .properties file

**Comment by JackyKwok42** [comment]
hi Justin, could you tell me how to fill in the keyfile in config? Since i am trying to do it but my kafka cluster is holding on Kubernetes. I have the json key called test.json but fail to config the connector.

![image](https://user-images.githubusercontent.com/42936090/59760665-64de1780-92c5-11e9-8df3-7efe01266242.png)
 
here are my config.
`{
          "name": "k-to-bq",
          "connector.class": "com.wepay.kafka.connect.bigquery.BigQuerySinkConnector",
          "topics": ["replica_db_.ztore.order_product"],
          "project": "ztore-data",
          "datasets": ".*=kafka.order_product",
          "keyfile": "/usr/share/confluent-hub-components/wepay-kafka-connect-bigquery/etc/test/test.json",
          "autoCreateTables": "false"
        }`
Error messages:
`{
    "name": "k-to-bq",
    "connector": {
        "state": "FAILED",
        "worker_id": "-------------",
        "trace": "com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException: Failed to access json key file\n\tat com.wepay.kafka.connect.bigquery.BigQueryHelper.connect(BigQueryHelper.java:65)\n\tat com.wepay.kafka.connect.bigquery.BigQuerySinkConnector.getBigQuery(BigQuerySinkConnector.java:92)\n\tat com.wepay.kafka.connect.bigquery.BigQuerySinkConnector.ensureExistingTables(BigQuerySinkConnector.java:132)\n\tat com.wepay.kafka.connect.bigquery.BigQuerySinkConnector.start(BigQuerySinkConnector.java:155)\n\tat org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:111)\n\tat org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:136)\n\tat org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:196)\n\tat org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:231)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:908)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.processConnectorConfigUpdates(DistributedHerder.java:345)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:317)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:219)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('t' (code 116)): was expecting double-quote to start field name\n at [Source: java.io.FileInputStream@1d0650e3; line: 1, column: 3]\n\tat com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1487)\n\tat com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)\n\tat com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:447)\n\tat com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleOddName(UTF8StreamJsonParser.java:1919)\n\tat com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parseName(UTF8StreamJsonParser.java:1617)\n\tat com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:700)\n\tat com.google.api.client.json.jackson2.JacksonParser.nextToken(JacksonParser.java:55)\n\tat com.google.api.client.json.JsonParser.startParsingObjectOrArray(JsonParser.java:243)\n\tat com.google.api.client.json.JsonParser.parse(JsonParser.java:442)\n\tat com.google.api.client.json.JsonParser.parseValue(JsonParser.java:781)\n\tat com.google.api.client.json.JsonParser.parse(JsonParser.java:382)\n\tat com.google.api.client.json.JsonParser.parse(JsonParser.java:355)\n\tat com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:87)\n\tat com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:81)\n\tat com.google.auth.oauth2.GoogleCredentials.fromStream(GoogleCredentials.java:149)\n\tat com.google.auth.oauth2.GoogleCredentials.fromStream(GoogleCredentials.java:127)\n\tat com.wepay.kafka.connect.bigquery.BigQueryHelper.connect(BigQueryHelper.java:61)\n\t... 16 more\n"
    },
    "tasks": [],
    "type": "sink"
}`
