### ISSUE TITLE
Attempted to reduce batch size below 1

### ISSUE THREAD

**Issue by rodolfo-picoreti** [wepay/kafka-connect-bigquery#247]
Hi!

I am trying out your connector, but I was unable to make it work :(

I am using Strimzi to create the kafka cluster on Kubernetes. I tried version 1.5.2 of your connector with the following properties:

```
connector.class=com.wepay.kafka.connect.bigquery.BigQuerySinkConnector
tasks.max=1

topics=mytopic
topicsToTables=mytopic=mytable
sanitizeTopics=true

autoCreateTables=false
autoUpdateSchemas=false

bufferSize=100000
maxWriteSize=10000
tableWriteWait=1000

batchWriter=com.wepay.kafka.connect.bigquery.write.batch.SingleBatchWriter
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false

project=bigquery-263917
datasets=mytopic=wine_stg
keyfile=/opt/kafka/external-configuration/bigquery-serviceaccount/sa.json
``` 

My BigQuery schema:

Field name | Type | Mode | Description
-- | -- | -- | --
example | STRING | NULLABLE |  

I've used the following command to publish to the topic:

```shell
./kafka-console-producer.sh --topic mytopic --broker-list localhost:9092
> { "example": "please work" }
```

The connector detects that a new message is present on the topic, but I am getting the following error:

```
2020-02-12 20:39:07,758 WARN No schema retriever class provided; auto schema updates are impossible (com.wepay.kafka.connect.bigquery.config.BigQuerySinkTaskConfig) [task-thread-hodor-0]
2020-02-12 20:39:07,763 INFO WorkerSinkTask{id=hodor-0} Sink task finished initialization and start (org.apache.kafka.connect.runtime.WorkerSinkTask) [task-thread-hodor-0]
2020-02-12 20:39:07,806 WARN [Consumer clientId=connector-consumer-hodor-0, groupId=connect-hodor] Error while fetching metadata with correlation id 2 : {mytopic=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient) [task-thread-hodor-0]
2020-02-12 20:39:07,806 INFO [Consumer clientId=connector-consumer-hodor-0, groupId=connect-hodor] Cluster ID: MC9fMW37QXySyHZdJBiWgw (org.apache.kafka.clients.Metadata) [task-thread-hodor-0]
2020-02-12 20:39:07,807 INFO [Consumer clientId=connector-consumer-hodor-0, groupId=connect-hodor] Discovered group coordinator cluster-kafka-1.cluster-kafka-brokers.kafka.svc:9092 (id: 2147483646 rack: null) (org.apache.kafka.clients.consumer.internals.AbstractCoordinator) [task-thread-hodor-0]
2020-02-12 20:39:07,807 INFO [Consumer clientId=connector-consumer-hodor-0, groupId=connect-hodor] (Re-)joining group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator) [task-thread-hodor-0]
2020-02-12 20:39:07,809 INFO [Consumer clientId=connector-consumer-hodor-0, groupId=connect-hodor] (Re-)joining group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator) [task-thread-hodor-0]
2020-02-12 20:39:10,812 INFO [Consumer clientId=connector-consumer-hodor-0, groupId=connect-hodor] Finished assignment for group at generation 13: {connector-consumer-hodor-0-0c849f59-24ba-4271-8753-2accf0d8959a=org.apache.kafka.clients.consumer.ConsumerPartitionAssignor$Assignment@9926137} (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator) [task-thread-hodor-0]
2020-02-12 20:39:10,815 INFO [Consumer clientId=connector-consumer-hodor-0, groupId=connect-hodor] Successfully joined group with generation 13 (org.apache.kafka.clients.consumer.internals.AbstractCoordinator) [task-thread-hodor-0]
2020-02-12 20:39:10,816 INFO [Consumer clientId=connector-consumer-hodor-0, groupId=connect-hodor] Adding newly assigned partitions: mytopic-0 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator) [task-thread-hodor-0]
2020-02-12 20:39:10,817 INFO [Consumer clientId=connector-consumer-hodor-0, groupId=connect-hodor] Found no committed offset for partition mytopic-0 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator) [task-thread-hodor-0]
2020-02-12 20:39:10,819 INFO [Consumer clientId=connector-consumer-hodor-0, groupId=connect-hodor] Resetting offset for partition mytopic-0 to offset 0. (org.apache.kafka.clients.consumer.internals.SubscriptionState) [task-thread-hodor-0]
^T2020-02-12 20:40:07,757 INFO Putting 0 records in the sink. (com.wepay.kafka.connect.bigquery.BigQuerySinkTask) [task-thread-hodor-0]
2020-02-12 20:41:07,760 INFO Putting 0 records in the sink. (com.wepay.kafka.connect.bigquery.BigQuerySinkTask) [task-thread-hodor-0]
2020-02-12 20:42:07,762 INFO Putting 0 records in the sink. (com.wepay.kafka.connect.bigquery.BigQuerySinkTask) [task-thread-hodor-0]
2020-02-12 20:43:07,763 INFO Putting 0 records in the sink. (com.wepay.kafka.connect.bigquery.BigQuerySinkTask) [task-thread-hodor-0]
2020-02-12 20:44:07,764 INFO Putting 0 records in the sink. (com.wepay.kafka.connect.bigquery.BigQuerySinkTask) [task-thread-hodor-0]
2020-02-12 20:45:07,764 INFO Putting 0 records in the sink. (com.wepay.kafka.connect.bigquery.BigQuerySinkTask) [task-thread-hodor-0]
2020-02-12 20:46:04,175 INFO Putting 1 records in the sink. (com.wepay.kafka.connect.bigquery.BigQuerySinkTask) [task-thread-hodor-0]
2020-02-12 20:46:04,433 ERROR Task failed with org.apache.kafka.connect.errors.ConnectException error: Attempted to reduce batch size below 1. (com.wepay.kafka.connect.bigquery.write.batch.KCBQThreadPoolExecutor) [pool-13-thread-5]
Exception in thread "pool-13-thread-5" org.apache.kafka.connect.errors.ConnectException: Attempted to reduce batch size below 1.
        at com.wepay.kafka.connect.bigquery.write.batch.TableWriter.getNewBatchSize(TableWriter.java:110)
        at com.wepay.kafka.connect.bigquery.write.batch.TableWriter.run(TableWriter.java:87)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-02-12 20:46:07,764 INFO Putting 0 records in the sink. (com.wepay.kafka.connect.bigquery.BigQuerySinkTask) [task-thread-hodor-0]
2020-02-12 20:46:07,765 ERROR WorkerSinkTask{id=hodor-0} Offset commit failed, rewinding to last committed offsets (org.apache.kafka.connect.runtime.WorkerSinkTask) [task-thread-hodor-0]
com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException: Some write threads encountered unrecoverable errors: org.apache.kafka.connect.errors.ConnectException; See logs for more detail
        at com.wepay.kafka.connect.bigquery.write.batch.KCBQThreadPoolExecutor.awaitCurrentTasks(KCBQThreadPoolExecutor.java:97)
        at com.wepay.kafka.connect.bigquery.BigQuerySinkTask.flush(BigQuerySinkTask.java:126)
        at org.apache.kafka.connect.sink.SinkTask.preCommit(SinkTask.java:125)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:379)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:208)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-02-12 20:46:07,765 INFO [Consumer clientId=connector-consumer-hodor-0, groupId=connect-hodor] Seeking to offset 0 for partition mytopic-0 (org.apache.kafka.clients.consumer.KafkaConsumer) [task-thread-hodor-0]
2020-02-12 20:46:07,765 ERROR WorkerSinkTask{id=hodor-0} Commit of offsets threw an unexpected exception for sequence number 7: null (org.apache.kafka.connect.runtime.WorkerSinkTask) [task-thread-hodor-0]
com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException: Some write threads encountered unrecoverable errors: org.apache.kafka.connect.errors.ConnectException; See logs for more detail
        at com.wepay.kafka.connect.bigquery.write.batch.KCBQThreadPoolExecutor.awaitCurrentTasks(KCBQThreadPoolExecutor.java:97)
        at com.wepay.kafka.connect.bigquery.BigQuerySinkTask.flush(BigQuerySinkTask.java:126)
        at org.apache.kafka.connect.sink.SinkTask.preCommit(SinkTask.java:125)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:379)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:208)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Thank you!

**Comment by pckushan** [comment]
I got the same issue with 1.5.2 latest version

> [2020-02-21 11:36:05,570] ERROR Task failed with org.apache.kafka.connect.errors.ConnectException error: Attempted to reduce batch size below 1. (com.wepay.kafka.connect.bigquery.write.batch.KCBQThreadPoolExecutor:68)
Exception in thread "pool-33-thread-1" org.apache.kafka.connect.errors.ConnectException: Attempted to reduce batch size below 1.
        at com.wepay.kafka.connect.bigquery.write.batch.TableWriter.getNewBatchSize(TableWriter.java:110)
        at com.wepay.kafka.connect.bigquery.write.batch.TableWriter.run(TableWriter.java:87)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2020-02-21 11:36:05,718] INFO [Worker clientId=connect-1, groupId=connect-cluster] Tasks [kcbq-connect2-0] configs updated (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1409)
[2020-02-21 11:36:06,222] INFO [Worker clientId=connect-1, groupId=connect-cluster] Finished starting connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1125)
[2020-02-21 11:36:06,225] INFO [Worker clientId=connect-1, groupId=connect-cluster] Handling task config update by restarting tasks [kcbq-connect2-0] (org.apache.kafka.connect.runtime.distributed.DistributedHerder:574)
[2020-02-21 11:36:06,225] INFO Stopping task kcbq-connect2-0 (org.apache.kafka.connect.runtime.Worker:708)
[2020-02-21 11:36:06,231] WARN WorkerSinkTask{id=kcbq-connect2-0} Offset commit failed during close (org.apache.kafka.connect.runtime.WorkerSinkTask:382)
[2020-02-21 11:36:06,231] ERROR WorkerSinkTask{id=kcbq-connect2-0} Commit of offsets threw an unexpected exception for sequence number 1: null (org.apache.kafka.connect.runtime.WorkerSinkTask:259)
com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException: Some write threads encountered unrecoverable errors: org.apache.kafka.connect.errors.ConnectException; See logs for more detail
        at com.wepay.kafka.connect.bigquery.write.batch.KCBQThreadPoolExecutor.awaitCurrentTasks(KCBQThreadPoolExecutor.java:97)
        at com.wepay.kafka.connect.bigquery.BigQuerySinkTask.flush(BigQuerySinkTask.java:119)
        at org.apache.kafka.connect.sink.SinkTask.preCommit(SinkTask.java:125)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:379)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:591)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:196)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2020-02-21 11:36:06,233] INFO [Consumer clientId=connector-consumer-kcbq-connect2-0, groupId=connect-kcbq-connect2] Revoke previously assigned partitions test-0 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:286)
[2020-02-21 11:36:06,234] WARN WorkerSinkTask{id=kcbq-connect2-0} Offset commit failed during close (org.apache.kafka.connect.runtime.WorkerSinkTask:382)
[2020-02-21 11:36:06,234] ERROR WorkerSinkTask{id=kcbq-connect2-0} Commit of offsets threw an unexpected exception for sequence number 2: null (org.apache.kafka.connect.runtime.WorkerSinkTask:259)


This triggers from **Attempted to reduce batch size below 1**

 I am not using the schema or avro, Im just getting the json payload from the topic. 
my configuration json file is below
--------
> {
   "name": "kcbq-connect",
   "config": {
     "connector.class": "com.wepay.kafka.connect.bigquery.BigQuerySinkConnector",
     "tasks.max" : "1",
     "topics" : "test",
     "sanitizeTopics" : "true",
     "key.converter": "org.apache.kafka.connect.storage.StringConverter",
     "value.converter":"org.apache.kafka.connect.json.JsonConverter",
	 "value.converter.schemas.enable":"false",
     "bufferSize": "100000",
     "maxWriteSize":"10000",
     "tableWriteWait": "1000",
	 "project": "bigdata-project-268607",
	 "batchWriter": "com.wepay.kafka.connect.bigquery.write.batch.SingleBatchWriter",
	 "datasets": ".*=bd_kafka_gcp",
     "keyfile" : "/home/kushan/docker/kafka-connector/bigdata-project-268607-118e1af00f3a.json"
   }
 }

In-order to write such json payload without a schema do we need to create the schema in BigQuery dataset ??

**Comment by perebaj** [comment]
I am using Strimzi to provisioning the Kafka cluster too. 
And I am not using schema registry to define schema of the tables and for this reason, table can not be created automatically by the Bquery sink plugin, to circumvent that, I am creating tables manually using the Google UI.
An important configuration to set up, is that table need to be partitioned, this configuration are passed to _timePartitioningType_ variable that default value is **DAY** [Confluent Doc](https://docs.confluent.io/kafka-connect-bigquery/current/kafka_connect_bigquery_config.html)

![image](https://user-images.githubusercontent.com/39134841/171438856-9d4877ea-4690-4bb6-9c55-0549b4ba3500.png)

Another important config is that the name of table and topic has to be the same, and config propertie: _bigQueryPartitionDecorator_ has to be set up to **false**
