### ISSUE TITLE
java.io.CharConversionException when deserializing messages

### ISSUE THREAD

**Issue by Fryuni** [wepay/kafka-connect-bigquery#254]
I am trying to get this connector to work in our environment.

This is the configuration that I'm using:
```
name=event-logger
connector.class=com.wepay.kafka.connect.bigquery.BigQuerySinkConnector
project=[OUR_PROJECT_ID]
datasets=.*=raw_topic_data
topics=all-messages
autoUpdateSchemas=true
bigQueryMessageTimePartitioning=true
sanitizeTopics=true
autoCreateTables=true
allBQFieldsNullable=true
tasks.max=1
schemaRegistryLocation=http://schema-registry-proxy:8081
maxWriteSize=10000
schemaRetriever=com.wepay.kafka.connect.bigquery.schemaregistry.schemaretriever.SchemaRegistrySchemaRetriever
convertDoubleSpecialValues=true
tableWriteWait=1000
bufferSize=100000
```

The schemas are converted correctly and the tables are being created, but then I get this error:
```
org.apache.kafka.common.errors.SerializationException: java.io.CharConversionException: Invalid UTF-32 character 0x1476664 (above 0x0010ffff) at char #1, byte #7)
Caused by: java.io.CharConversionException: Invalid UTF-32 character 0x1476664 (above 0x0010ffff) at char #1, byte #7)
	at com.fasterxml.jackson.core.io.UTF32Reader.reportInvalid(UTF32Reader.java:195)
	at com.fasterxml.jackson.core.io.UTF32Reader.read(UTF32Reader.java:158)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._loadMore(ReaderBasedJsonParser.java:258)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:2353)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:671)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4231)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2725)
	at org.apache.kafka.connect.json.JsonDeserializer.deserialize(JsonDeserializer.java:58)
	at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:353)
	at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:86)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$1(WorkerSinkTask.java:485)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:485)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:465)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

There is a `JsonConverter` in the stack trace while I'm using Avro... that seems likely to be the problem to me, but I haven't found any configuration for this.

**Comment by C0urante** [comment]
Assuming you'd like to use the Confluent Avro converter (which seems likely given your use of Schema Registry), can you try adding these lines to your connector config?

```properties
value.converter.schema.registry.url=http://schema-registry-proxy:8081
value.converter=io.confluent.connect.avro.AvroConverter
```

**Comment by Fryuni** [comment]
Just tried. Same error

**Comment by C0urante** [comment]
Same stack trace, too?

**Comment by Fryuni** [comment]
Yep

**Comment by C0urante** [comment]
Try adding these as well?

```properties
key.converter=io.confluent.connect.avro.AvroConverter
key.converter.schema.registry.url=http://schema-registry-proxy:8081
```

**Comment by Fryuni** [comment]
Thanks, that solved it.

The quickstart [here](https://docs.confluent.io/current/connect/kafka-connect-bigquer) using Avro do not include those options, that is what i followed.
